### ISSUE TITLE
Stuck at migration

### ISSUE THREAD

**Issue by manuchap** [galetahub/sunrise-core#1]
Hi there! I'really like to try your app but I'm stuck during migration. Bundle installed everything fine. Here my trace:

----------------------------------------------------------------------------------------------------------------------------------------- 00:21:37
user@user:~/Sites/sunrise$ rake db:migrate --trace
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
private method `id' called for #<StructureType:0x00000103f2b800 @kind="page", @id=1>
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/galetahub-enum_field-0.1.4/lib/enum_field/builder.rb:73:in`save'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/galetahub-enum_field-0.1.4/lib/enum_field/builder.rb:16:in `member'
/Users/user/Sites/sunrise/app/models/defaults/structure_type.rb:3:in`block in class:StructureType'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/galetahub-enum_field-0.1.4/lib/enum_field/define_enum.rb:6:in `define_enum'
/Users/user/Sites/sunrise/app/models/defaults/structure_type.rb:2:in`class:StructureType'
/Users/user/Sites/sunrise/app/models/defaults/structure_type.rb:1:in `<top (required)>'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:454:in`load'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:454:in `block in load_file'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:593:in`new_constants_in'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:453:in `load_file'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:340:in`require_or_load'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:487:in `load_missing_constant'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:183:in`block in const_missing'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:181:in `each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:181:in`const_missing'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/inflector/methods.rb:124:in `block in constantize'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/inflector/methods.rb:123:in`each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/inflector/methods.rb:123:in `constantize'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/core_ext/string/inflections.rb:43:in`constantize'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/galetahub-enum_field-0.1.4/lib/enum_field/enumerated_attribute.rb:41:in `enumerated_attribute'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/sunrise-core-0.2.0/lib/sunrise/models/structure.rb:14:in`block in extended'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/sunrise-core-0.2.0/lib/sunrise/models/structure.rb:13:in `class_eval'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/sunrise-core-0.2.0/lib/sunrise/models/structure.rb:13:in`extended'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/sunrise-core-0.2.0/lib/sunrise/models/structure.rb:7:in `extend'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/sunrise-core-0.2.0/lib/sunrise/models/structure.rb:7:in`included'
/Users/user/Sites/sunrise/app/models/defaults/structure.rb:2:in `include'
/Users/user/Sites/sunrise/app/models/defaults/structure.rb:2:in`class:Structure'
/Users/user/Sites/sunrise/app/models/defaults/structure.rb:1:in `<top (required)>'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:454:in`load'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:454:in `block in load_file'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:593:in`new_constants_in'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:453:in `load_file'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:340:in`require_or_load'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:487:in `load_missing_constant'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:183:in`block in const_missing'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:181:in `each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:181:in`const_missing'
/Users/user/Sites/sunrise/spec/factories/structure_factory.rb:3:in `block in <top (required)>'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/factory_girl-2.0.5/lib/factory_girl/syntax/default.rb:12:in`instance_eval'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/factory_girl-2.0.5/lib/factory_girl/syntax/default.rb:12:in `run'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/factory_girl-2.0.5/lib/factory_girl/syntax/default.rb:7:in`define'
/Users/user/Sites/sunrise/spec/factories/structure_factory.rb:2:in `<top (required)>'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:235:in`load'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:235:in `block in load'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:225:in`block in load_dependency'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:593:in `new_constants_in'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:225:in`load_dependency'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:235:in `load'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/factory_girl-2.0.5/lib/factory_girl/find_definitions.rb:20:in`block (2 levels) in find_definitions'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/factory_girl-2.0.5/lib/factory_girl/find_definitions.rb:19:in `each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/factory_girl-2.0.5/lib/factory_girl/find_definitions.rb:19:in`block in find_definitions'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/factory_girl-2.0.5/lib/factory_girl/find_definitions.rb:15:in `each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/factory_girl-2.0.5/lib/factory_girl/find_definitions.rb:15:in`find_definitions'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/factory_girl_rails-1.1.0/lib/factory_girl_rails/railtie.rb:11:in `block in <class:Railtie>'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/lazy_load_hooks.rb:34:in`call'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/lazy_load_hooks.rb:43:in`block in run_load_hooks'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/lazy_load_hooks.rb:42:in `each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/lazy_load_hooks.rb:42:in`run_load_hooks'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/application/finisher.rb:46:in `block in <module:Finisher>'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/initializable.rb:25:in`instance_exec'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/initializable.rb:25:in `run'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/initializable.rb:50:in`block in run_initializers'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/initializable.rb:49:in `each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/initializable.rb:49:in`run_initializers'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/application.rb:134:in `initialize!'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/application.rb:77:in`method_missing'
/Users/user/Sites/sunrise/config/environment.rb:5:in `<top (required)>'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:239:in`require'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:239:in `block in require'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:225:in`block in load_dependency'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:593:in `new_constants_in'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:225:in`load_dependency'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/activesupport-3.0.11/lib/active_support/dependencies.rb:239:in `require'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/application.rb:103:in`require_environment!'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/railties-3.0.11/lib/rails/application.rb:218:in `block in initialize_tasks'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:157:in`block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/bin/rake:19:in`load'
/Users/user/.rvm/gems/ruby-1.9.2-p290@sunrise/bin/rake:19:in `<main>'
Tasks: TOP => db:migrate => environment
----------------------------------------------------------------------------------------------------------------------------------------- 00:21:53

**Comment by superp** [comment]
This gem does not support ruby-1.9 yet.
Try to use ruby 1.8.7

**Comment by manuchap** [comment]
Dude! Dunno what I'm doing wrong but I'm stuck again, but one step earlier now…
Here's what I did:
- installed 1.8.7-p352 with rvm
- created sunrise gemset
- cloned sunrise repo
- cd to cloned repo
- bundle installed fine
  (2 warnings during bundle install:
  Installing abstract (1.0.0) WARNING: abstract-1.0.0 has an invalid nil value for @cert_chain
  Installing builder (2.1.2) WARNING: builder-2.1.2 has an invalid nil value for @cert_chain)
- copy paste "rails generate sunrise:install"
- got this:

manuite@Manuite:~/Sites/sunrise-core$ rails generate sunrise:install
Usage:
  rails new APP_PATH [options]

Options:
  -G, [--skip-git]            # Skip Git ignores and keeps
  -b, [--builder=BUILDER]     # Path to an application builder (can be a filesystem path or URL)
  -r, [--ruby=PATH]           # Path to the Ruby binary of your choice
                              # Default: /Users/manuite/.rvm/rubies/ruby-1.8.7-p352/bin/ruby
      [--edge]                # Setup the application with Gemfile pointing to Rails repository
      [--dev]                 # Setup the application with Gemfile pointing to your Rails checkout
  -d, [--database=DATABASE]   # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                              # Default: sqlite3
      [--skip-gemfile]        # Don't create a Gemfile
  -J, [--skip-prototype]      # Skip Prototype files
  -O, [--skip-active-record]  # Skip Active Record files
  -T, [--skip-test-unit]      # Skip Test::Unit files
  -m, [--template=TEMPLATE]   # Path to an application template (can be a filesystem path or URL)

Runtime options:
  -f, [--force]    # Overwrite files that already exist
  -s, [--skip]     # Skip files that already exist
  -p, [--pretend]  # Run but do not make any changes
  -q, [--quiet]    # Supress status output

Rails options:
  -v, [--version]  # Show Rails version number and quit
  -h, [--help]     # Show this help message and quit

Description:
    The 'rails new' command creates a new Rails application with a default
    directory structure and configuration at the path you specify.

Example:
    rails new ~/Code/Ruby/weblog

```
This generates a skeletal Rails installation in ~/Code/Ruby/weblog.
See the README in the newly created application to get going.
```

Which generated a me@puzzled_to_the_max…
I can't recall how I got it further at first try.
Thank for reading, I'm pretty trim with ruby but I never give up ;-)

**Comment by superp** [comment]
sunrise-core is not a rails project, it's just a library for this.

First of all you must generate a rails project:

```
rails new my_project -d mysql -J
cd my_project
```

After this, include gems to Gemfile:

```
gem "rails", "~> 3.0.10"
gem "mysql2", "~> 0.2.13"
gem 'inherited_resources'
gem 'has_scope'
gem 'carrierwave'
gem 'mini_magick'
gem 'mime-types'
gem 'kaminari'
gem 'cancan'
gem 'cancan_namespace'
gem 'devise'
gem 'simple_form'
gem 'awesome_nested_set'
gem 'fastercsv'
gem 'ckeditor'  

gem 'galetahub-enum_field', '~> 0.1.4', :require => 'enum_field'
gem 'galetahub-salty_slugs', '~> 1.0.0', :require => 'salty_slugs'  

gem "sunrise-cms"
gem "sunrise-file-upload"    

group :test, :development do
  gem "rspec-rails", "~> 2.6.1"
  gem "database_cleaner", "~> 0.6.7"
  gem "factory_girl_rails", "~> 1.1.0"
  gem "fuubar"
end
```

Install this gems:

```
bundle install --path vendor/bundle
```

And only now you can run command:

```
 rails generate sunrise:install
```

**Comment by superp** [comment]
rails version must be > 3.0 and < 3.1
